version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: gen3-fence-postgres
    networks:
      - devnet
    volumes:
      - psqldata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  # fence-service:
  #   build: .
  #   container_name: fence-service
  #   networks:
  #     - devnet
  #   volumes:
  #     - ./Secrets/TLS/service.crt:/usr/local/share/ca-certificates/cdis-ca.crt
  #     - ./keys/dev:/fence/keys/dev
  #     - ./fence-config.yaml:/fence/fence-config.yaml
  #     - ./fence:/fence/fence
  #   ports:
  #     - 443:443
  #     - 80:80
  #   healthcheck:
  #     test: [ "CMD-SHELL", "curl -f http://localhost/_status" ]
  #     interval: 60s
  #     timeout: 5s
  #     retries: 3
  #   environment:
  #     - PYTHONPATH=/var/www/fence
  #     - USER_API=http://localhost/user
  #     - GEN3_DEBUG=True
  #     - USER_SERVICE_BASE_URL=https://cngooq0hll.execute-api.us-east-2.amazonaws.com/user/
  #     - AWS_ACCESS_KEY_ID=AKIAWSU52FC73GM6GJHN
  #     - AWS_SECRET_ACCESS_KEY=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
  #     - AWS_COGNITO_REGION=us-east-2
  #     - AWS_COGNITO_APP_CLIENT_ID=5g5kvm7idj6usg5b4uqr60nb4i
  #     - AWS_COGNITO_APP_CLIENT_SECRET=14t115g1a1cbhtaj5a00fp3c1n4ljdfbvvdbn0rvec8ke35883ci
  #     - AWS_COGNITO_USER_POOL_ID=us-east-2_9wu6U8aJf

  #   depends_on:
  #     - postgres

networks:
  devnet:
volumes:
  psqldata:
  pgadmindata: